version: "3.7"
services:
  wordpress:
    image: videogamearmy/wordpress-docker-sec:5.0.3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - db-net
      - nginx-net
      - redis-net

  nginx:
    image: videogamearmy/nginx-wordpress-docker-sec:1.15.8
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
     - wordpress
    volumes:
     - wordpress-data:/var/www/html/
    ports:
      - target: 80
        published: 80
        protocol: tcp
    environment:
      POST_MAX_SIZE: 128m
    networks:
      - nginx-net

  redis:
    image: redis:5.0.3-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  db:
    image: mysql:8.0.13
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
    networks:
      - db-net
    volumes:
      - db-data:/var/lib/mysql

networks:
  db-net:
    driver: overlay
  nginx-net:
    driver: overlay
  redis-net:
    driver: overlay

secrets:
  db_password:
    external: true
  db_root_password:
    external: true

volumes:
  wordpress-data:
  redis-data:
  db-data: