version: "3.7"
services:
  wordpress:
    image: videogamearmy/wordpress-docker-sec:5.0.3
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wp-data:/var/www/html
    networks:
      - wp-net
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '10'

  wpcli:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: wordpress:cli-2.1.0-php7.3
    volumes:
        - ./conf/php/extra.ini:/usr/local/etc/php/conf.d/extra.ini
        - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf 
    depends_on:
      - db
    entrypoint: /bin/wp-cli.phar --allow-root
    command: "--info"
    networks:
      - wp-net
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '10'

  nginx:
    image: videogamearmy/nginx-wordpress-docker-sec:1.15.8
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    depends_on:
     - wordpress
    volumes:
        - ./www:/www   
        - ./conf/php/extra.ini:/usr/local/etc/php/conf.d/extra.ini
        - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf 
    ports:
      - target: 80
        published: 80
        protocol: tcp
    environment:
      POST_MAX_SIZE: 128m
    networks:
      - nginx-net
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '10'

  redis:
    image: redis:5.0.3-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '10'

  db:
    image: mysql:8.0.13
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ./backups:/backups
      - ./conf/mariadb:/etc/mysql/conf.d
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - wp-net
networks:
  wp-net:
    driver: overlay
  nginx-net:
    driver: overlay
  redis-net:
    driver: overlay

secrets:
  db_password:
    external: true
  db_root_password:
    external: true

volumes:
  wp-data:
  redis-data:
  db-data: